// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI（migrate等）はSession pooler経由の直結URLを使う。実行時はadapter側でDATABASE_URL（Transaction pooler）を使用
    url: process.env["DIRECT_URL"],
  },
});
